export const SET_SELECTED_USER = "SET_SELECTED_USER";
export const FETCH_USER_REQUEST = "FETCH_USER_REQUEST";
export const FETCH_USERS_SUCCESS = "FETCH_USERS_SUCCESS";
export const FETCH_USERS_FAILURE = "FETCH_USERS_FAILURE";
export const REGISTER_USER = "REGISTER_USER";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const FETCH_LOGIN_REQUEST = "FETCH_LOGIN_REQUEST";
//types centre
export const SET_SELECTED_CENTER = "SET_SELECTED_CENTER";
export const FETCH_CENTERS_REQUEST = "FETCH_CENTERS_REQUEST";
export const FETCH_CENTERS_SUCCESS = "FETCH_CENTERS_SUCCESS";
export const FETCH_CENTERS_FAILURE = "FETCH_CENTERS_FAILURE";
export const SET_DISPLAYED = "SET_DISPLAYED";
export const SET_DISPLAY_UPDATE = "SET_DISPLAY_UPDATE";
export const SET_DISPLAY_UPDATE_VAC = "SET_DISPLAY_UPDATE_VAC";

export const FETCH_CENTER_BY_ID = "FETCH_CENTER_BY_ID";
export const ADD_CENTER = "ADD_CENTER";
export const UPDATE_CENTER = "UPDATE_CENTER";
export const DELETE_CENTER = "DELETE_CENTER";
export const ADD_VACCINE_TO_CENTER = "ADD_VACCINE_TO_CENTER";

//types pharmacie
export const SET_SELECTED_PHARMACY = "SET_SELECTED_PHARMACY";
export const FETCH_PHARMACIES_REQUEST = "FETCH_PHARMACIES_REQUEST";
export const FETCH_PHARMACIES_SUCCESS = "FETCH_PHARMACIES_SUCCESS";
export const FETCH_PHARMACIES_FAILURE = "FETCH_PHARMACIES_FAILURE";
export const SET_DISPLAYED_PHARMACY = "SET_DISPLAYED_PHARMACY";
export const FETCH_PHARMACY_BY_ID = "FETCH_PHARMACY_BY_ID";
export const ADD_PHARMACY = "ADD_PHARMACY";
export const UPDATE_PHARMACY = "UPDATE_PHARMACY";
export const DELETE_PHARMACY = "DELETE_PHARMACY";

//types vaccin
export const SET_SELECTED_VACCINE = "SET_SELECTED_VACCINE";
export const FETCH_VACCINES_REQUEST = "FETCH_VACCINES_REQUEST";
export const FETCH_VACCINES_SUCCESS = "FETCH_VACCINES_SUCCESS";
export const FETCH_VACCINES_FAILURE = "FETCH_VACCINES_FAILURE";

export const FETCH_VACCINE_BY_ID = "FETCH_VACCINE_BY_ID";
export const ADD_VACCINE = "ADD_VACCINE";
export const UPDATE_VACCINE = "UPDATE_VACCINE";
export const DELETE_VACCINE = "DELETE_VACCINE";
export const SET_DISPLAYED_VACCINE = "SET_DISPLAYED_VACCINE";
export const SET_DISPLAY_UPDATE_VACCINE = "SET_DISPLAY_UPDATE_VACCINE";

//types register in center

export const REGISTER_CENTER = "REGISTER_CENTER";

//types users
export const ADD_USER = "ADD_USER";
export const UPDATE_USER = "UPDATE_USER";
export const DELETE_USER = "DELETE_USER";
export const GET_ALL_USER = "GET_ALL_USER";
export const SET_DISPLAYED_USER = "SET_DISPLAYED_USER";
export const SET_DISPLAY_UPDATE_USER = "SET_DISPLAY_UPDATE_USER";
export const GET_USER_BY_CIN = "GET_USER_BY_CIN";

//RDV actions type
export const ADD_RDV = "ADD_RDV";
export const UPDATE_RDV = "UPDATE_RDV";

//ERROR
export const SET_ERRORS = "SET_ERRORS"
export const CLEAR_ERRORS = "CLEAR_ERRORS"
export const SET_FLAG = "SET_FLAG"



//jounées porte ouverte
export const ADD_OPEN_DAY = "ADD_OPEN_DAY";
export const SET_SELECTED_OPEN_DAY = "SET_SELECTED_OPEN_DAY";
export const SET_DISPLAYED_OPEN_DAY = "SET_DISPLAYED_OPEN_DAY";
export const GET_ALL_OPEN_DAYS = "GET_ALL_OPEN_DAYS";
export const SET_DISPLAY_UPDATE_OPEN_DAY = "SET_DISPLAY_UPDATE_OPEN_DAY";
export const UPDATE_OPEN_DAY = "UPDATE_OPEN_DAY"; // we need it ?
